//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://journalWS.com/", ConfigurationName="ServiceReference1.ArticleService")]
    public interface ArticleService
    {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://journalWS.com/ArticleService/ajouterArticleRequest", ReplyAction="http://journalWS.com/ArticleService/ajouterArticleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference1.ajouterArticleResponse ajouterArticle(ServiceReference1.ajouterArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://journalWS.com/ArticleService/ajouterArticleRequest", ReplyAction="http://journalWS.com/ArticleService/ajouterArticleResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ajouterArticleResponse> ajouterArticleAsync(ServiceReference1.ajouterArticleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://journalWS.com/")]
    public partial class article
    {
        
        private int appreciationField;
        
        private int depreciationField;
        
        private string texteField;
        
        private string titreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int appreciation
        {
            get
            {
                return this.appreciationField;
            }
            set
            {
                this.appreciationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int depreciation
        {
            get
            {
                return this.depreciationField;
            }
            set
            {
                this.depreciationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string texte
        {
            get
            {
                return this.texteField;
            }
            set
            {
                this.texteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string titre
        {
            get
            {
                return this.titreField;
            }
            set
            {
                this.titreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterArticle", WrapperNamespace="http://journalWS.com/", IsWrapped=true)]
    public partial class ajouterArticleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://journalWS.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.article article;
        
        public ajouterArticleRequest()
        {
        }
        
        public ajouterArticleRequest(ServiceReference1.article article)
        {
            this.article = article;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterArticleResponse", WrapperNamespace="http://journalWS.com/", IsWrapped=true)]
    public partial class ajouterArticleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://journalWS.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ajouterArticleResponse()
        {
        }
        
        public ajouterArticleResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ArticleServiceChannel : ServiceReference1.ArticleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ArticleServiceClient : System.ServiceModel.ClientBase<ServiceReference1.ArticleService>, ServiceReference1.ArticleService
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ArticleServiceClient() : 
                base(ArticleServiceClient.GetDefaultBinding(), ArticleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ArticleServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ArticleServiceClient.GetBindingForEndpoint(endpointConfiguration), ArticleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArticleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArticleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.ajouterArticleResponse ServiceReference1.ArticleService.ajouterArticle(ServiceReference1.ajouterArticleRequest request)
        {
            return base.Channel.ajouterArticle(request);
        }
        
        public string ajouterArticle(ServiceReference1.article article)
        {
            ServiceReference1.ajouterArticleRequest inValue = new ServiceReference1.ajouterArticleRequest();
            inValue.article = article;
            ServiceReference1.ajouterArticleResponse retVal = ((ServiceReference1.ArticleService)(this)).ajouterArticle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ajouterArticleResponse> ServiceReference1.ArticleService.ajouterArticleAsync(ServiceReference1.ajouterArticleRequest request)
        {
            return base.Channel.ajouterArticleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ajouterArticleResponse> ajouterArticleAsync(ServiceReference1.article article)
        {
            ServiceReference1.ajouterArticleRequest inValue = new ServiceReference1.ajouterArticleRequest();
            inValue.article = article;
            return ((ServiceReference1.ArticleService)(this)).ajouterArticleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArticleServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArticleServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ArticleService/ArticleService");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ArticleServiceClient.GetBindingForEndpoint(EndpointConfiguration.ArticleServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ArticleServiceClient.GetEndpointAddress(EndpointConfiguration.ArticleServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ArticleServicePort,
        }
    }
}
